/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacyRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Medicines.MedicineDirectory;
import Business.Medicines.Medicines;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.medicineWorkRequest;
//import Business.WorkQueue.medicineWorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vasundhara
 */
public class AddMedicineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddMedicineJPanel
     */
    private JPanel userProcessContainer;
    private MedicineDirectory medicineList;
    private PharmacyOrganization pharmacyOrganization;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem business;
    Organization org;
    

    public AddMedicineJPanel(JPanel userProcessContainer, UserAccount userAccount,Enterprise enterprise, EcoSystem business, MedicineDirectory medicineList, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.medicineList = medicineList;
        this.org = organization;
        this.pharmacyOrganization = (PharmacyOrganization)org;
        this.enterprise = enterprise;
        this.business = business;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) MedicinejTable1.getModel();
        dtm.setRowCount(0);
        for(WorkRequest request: pharmacyOrganization.getWorkQueue().getWorkRequestList()){
            if(request instanceof medicineWorkRequest){
        //for(Medicines m: medicineList.getMedicineList()){
            Object[] row = new Object[3];
            medicineWorkRequest mediRequest = (medicineWorkRequest)request;
            row[0] = mediRequest;
            row[1] = mediRequest.getQty();
            row[2] = mediRequest.getExpDate();
            
            dtm.addRow(row);
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        MedicinejTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        MedicineNamejTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        qtyjTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ExpiryDatejTextField1 = new javax.swing.JTextField();
        AddjButton = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MedicinejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Available Quantity", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(MedicinejTable1);
        if (MedicinejTable1.getColumnModel().getColumnCount() > 0) {
            MedicinejTable1.getColumnModel().getColumn(0).setResizable(false);
            MedicinejTable1.getColumnModel().getColumn(1).setResizable(false);
            MedicinejTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 58, -1, 95));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Medicine Name :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 201, 150, 30));

        MedicineNamejTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MedicineNamejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineNamejTextField1ActionPerformed(evt);
            }
        });
        add(MedicineNamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 201, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Available Quantity :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 249, 150, 30));

        qtyjTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(qtyjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 249, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Expiry Date :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 297, 150, 30));

        ExpiryDatejTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(ExpiryDatejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 297, 150, 30));

        AddjButton.setBackground(new java.awt.Color(0, 0, 0));
        AddjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddjButton.setForeground(new java.awt.Color(255, 255, 255));
        AddjButton.setText("Add");
        AddjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddjButtonActionPerformed(evt);
            }
        });
        add(AddjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 368, 100, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 368, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AddjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddjButtonActionPerformed
        // TODO add your handling code here:
        
            String medicineName = MedicineNamejTextField1.getText();
            int availCount = Integer.parseInt(qtyjTextField1.getText());
            String eDate = ExpiryDatejTextField1.getText();
            //Date expDate = new SimpleDateFormat("MM/DD/YYYY").parse(eDate);
            
            //Medicines medicines = new Medicines(medicineName, availCount, expDate);
            Medicines medicines = medicineList.addMedicine(medicineName, availCount, eDate);
            medicineWorkRequest mRequest = new medicineWorkRequest();
            //medicineWorkRequest mediRequest = new medicineWorkRequest();
            mRequest.setMediName(medicineName);
            mRequest.setQty(availCount);
            mRequest.setExpDate(eDate);
            /*medicines.setMedicineName(medicineName);
            medicines.setAvailCount(availCount);
            medicines.setExpDate(eDate);*/
            for (Network network : business.getNetworkList()) {
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        if (enterprise instanceof HospitalEnterprise) {
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                if (organization instanceof PharmacyOrganization) {
                                    org = organization;
                                    break;
                                }
                            }
                        }

                    }
                }
                if (org != null) {
                    //System.out.println("userinterface.Farmer.FarmerComplaintRegistrationJPanel.requestTestJButtonActionPerformed()");
                    org.getWorkQueue().getWorkRequestList().add(mRequest);
                    userAccount.getWorkQueue().getWorkRequestList().add(mRequest);

                    //JOptionPane.showMessageDialog(null, "You have successfully added Patient Record !", "Information", JOptionPane.INFORMATION_MESSAGE);

                }
            populateTable();
            
            MedicineNamejTextField1.setText("");
            qtyjTextField1.setText("");
            ExpiryDatejTextField1.setText("");
               
        
    }//GEN-LAST:event_AddjButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void MedicineNamejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineNamejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineNamejTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddjButton;
    private javax.swing.JTextField ExpiryDatejTextField1;
    private javax.swing.JTextField MedicineNamejTextField1;
    private javax.swing.JTable MedicinejTable1;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField qtyjTextField1;
    // End of variables declaration//GEN-END:variables
}
