/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacyRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Medicines.MedicineDirectory;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.medicineWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.medicineWorkFlowRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
//import userinterface.LabAssistantRole.ProcessWorkRequestJPanel;

/**
 *
 * @author vasundhara
 */
public class PharmacyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private PharmacyOrganization pharmacyOrganization;
    private EcoSystem business;
    private Enterprise enterprise;
    private UserAccount userAccount;
    //private EcoSystem business;
    
    //private JPanel userProccessContainer;
    private MedicineDirectory medicineList;
    
    /*public PharmacyWorkAreaJPanel(JPanel userProcessContainer, MedicineDirectory medicineList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        
    }*/

    

    public PharmacyWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pharmacyOrganization = (PharmacyOrganization)organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.medicineList = new MedicineDirectory() ;
        this.business = business;
        
        valueLabel.setText(enterprise.getName());
        populateRequestMedicineJTable();
    }
    
    public void populateRequestMedicineJTable(){
        DefaultTableModel model = (DefaultTableModel) medicineRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : pharmacyOrganization.getWorkQueue().getWorkRequestList()){
            if(request instanceof medicineWorkFlowRequest){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();
            /*String result = ((medicineWorkRequest) request).getMediName();
            row[3] = result == null ? "Waiting" : result;*/
            
            model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicineRequestJTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        processjButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        assignjButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicineRequestJTable.setBackground(new java.awt.Color(0, 0, 0));
        medicineRequestJTable.setForeground(new java.awt.Color(255, 255, 255));
        medicineRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(medicineRequestJTable);
        if (medicineRequestJTable.getColumnModel().getColumnCount() > 0) {
            medicineRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            medicineRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            medicineRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            medicineRequestJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 441, 96));

        refreshJButton.setBackground(new java.awt.Color(0, 0, 0));
        refreshJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refreshJButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        processjButton.setBackground(new java.awt.Color(0, 0, 0));
        processjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        processjButton.setForeground(new java.awt.Color(255, 255, 255));
        processjButton.setText("Process");
        processjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processjButtonActionPerformed(evt);
            }
        });
        add(processjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 93, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 127, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 158, 26));

        assignjButton2.setBackground(new java.awt.Color(0, 0, 0));
        assignjButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        assignjButton2.setForeground(new java.awt.Color(255, 255, 255));
        assignjButton2.setText("Assign to me");
        assignjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignjButton2ActionPerformed(evt);
            }
        });
        add(assignjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Pharmacy Work Area Screen");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
       // populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void assignjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignjButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = medicineRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        
        WorkRequest request = (WorkRequest)medicineRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        populateRequestMedicineJTable();
    }//GEN-LAST:event_assignjButton2ActionPerformed

    private void processjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = medicineRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select a row");
        }
        
        medicineWorkFlowRequest request = (medicineWorkFlowRequest)medicineRequestJTable.getValueAt(selectedRow, 0);
     
        request.setStatus("Processing");
        
        ProcessMedicineRequestJPanel processMedicineRequestJPanel = new ProcessMedicineRequestJPanel(userProcessContainer, request);
        userProcessContainer.add("ProcessMedicineRequestJPanel", processMedicineRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_processjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignjButton2;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicineRequestJTable;
    private javax.swing.JButton processjButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
