/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabAssistantRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.MCHBEnterprise;
import Business.Network.Network;
import Business.Organization.CareTakerOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.VitalSigns.VitalSignsHistory;
import Business.WorkQueue.WorkRequest;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.VitalSigns.VitalSigns;
import Business.WorkQueue.DoctorWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author my pc
 */
public class AddPatientVitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPatientVitalJPanel
     */
    private JPanel userProcessContainer;
    private WorkRequest request;
    private VitalSignsHistory vitalSignsHistory;
   // private Patient patient;
    private LabTestWorkRequest labtestrequest;
    private LabOrganization labOrganization;
    private EcoSystem system;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization org;
    
    public AddPatientVitalJPanel(JPanel userProcessContainer,WorkRequest labtestrequest,VitalSignsHistory vitalSignsHistory,UserAccount userAccount,Organization organization,Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        this.vitalSignsHistory=vitalSignsHistory;
        this.labtestrequest=(LabTestWorkRequest) labtestrequest;
        this.enterprise=enterprise;
        this.system=system;
        this.org=organization;
        this.labOrganization=(LabOrganization) organization;
        this.userAccount=userAccount;
        populatePatientDetail();
    }
    public void populatePatientDetail(){
      nameTextField.setText(labtestrequest.getName());
      dobTextField.setText(labtestrequest.getDateOfBirth());
      domTextField.setText(labtestrequest.getDateOfMarriage());
      contactNameTextField.setText(labtestrequest.getEmergencyContactName());
      contactnumTextField.setText(Double.toString(labtestrequest.getEmergencyContactNumber()));
      cityTextField.setText(labtestrequest.getCity());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dobTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        domTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contactNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        contactnumTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bloodPressureTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        haemoglobinTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tempTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pulseTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        respirationTextField = new javax.swing.JTextField();
        addPatientBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        numMonthsTextField = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, -1));

        nameTextField.setEnabled(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Date of Birth");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        dobTextField.setEnabled(false);
        dobTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(dobTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Date of Marriage");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));

        domTextField.setEnabled(false);
        jPanel1.add(domTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Emergency Contact Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 150, -1));

        contactNameTextField.setEnabled(false);
        jPanel1.add(contactNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Emergency Contact Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 170, -1));

        contactnumTextField.setEnabled(false);
        contactnumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnumTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(contactnumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 120, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("City");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 40, -1));

        cityTextField.setEnabled(false);
        jPanel1.add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 120, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create Vital Signs Report ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 310, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Blood Pressure");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 100, -1));

        bloodPressureTextField.setText("160");
        jPanel1.add(bloodPressureTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 120, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Test Results");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 110, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Haemoglobin");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 90, -1));

        haemoglobinTextField.setText("41");
        jPanel1.add(haemoglobinTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 120, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Temparature");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 100, -1));

        tempTextField.setText("98");
        jPanel1.add(tempTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 120, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Pulse Rate");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 90, -1));

        pulseTextField.setText("77");
        jPanel1.add(pulseTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 120, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Respiration Rate");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 110, -1));

        respirationTextField.setText("17");
        jPanel1.add(respirationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 120, -1));

        addPatientBtn.setBackground(new java.awt.Color(0, 0, 0));
        addPatientBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addPatientBtn.setForeground(new java.awt.Color(255, 255, 255));
        addPatientBtn.setText("Add Patient Result");
        addPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addPatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("No of Months");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 90, -1));

        numMonthsTextField.setText("2");
        jPanel1.add(numMonthsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void dobTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTextFieldActionPerformed

    private void contactnumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnumTextFieldActionPerformed

    private void addPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientBtnActionPerformed
        double bloodpressure=0;
        try
        { bloodpressure = Double.parseDouble(bloodPressureTextField.getText());
        }
        catch(Exception e)
        {   
            JOptionPane.showMessageDialog(null, "Enter Valid Blood Pressure");
            return;
        }
        double haemoglobin = Double.parseDouble(haemoglobinTextField.getText());
        double temp = Double.parseDouble(tempTextField.getText());
        int pulse = Integer.parseInt(pulseTextField.getText());
        int resp = Integer.parseInt(respirationTextField.getText());
        String name = nameTextField.getText();
        String dob = dobTextField.getText();
        String dom = domTextField.getText();
        String contactname= contactNameTextField.getText();
        double contactnumber= Double.parseDouble(contactnumTextField.getText());
        String city = cityTextField.getText();
        int pregnancyperiod= Integer.parseInt(numMonthsTextField.getText());
        
        /*for(WorkRequest r :labOrganization.getWorkQueue().getWorkRequestList()){
            if(r instanceof LabTestWorkRequest){
                r.setStatus("LabProcessing");
            }
        }*/
        
        VitalSigns vitalSigns = vitalSignsHistory.addVitalSigns(name,dob,dom,contactname,contactnumber,city,bloodpressure,haemoglobin,temp,pulse,resp,pregnancyperiod);
        DoctorWorkRequest doctorWorkRequest = new DoctorWorkRequest();
        doctorWorkRequest.setPatientName(name);
        doctorWorkRequest.setDateOfBirth(dob);
        doctorWorkRequest.setDateOfMarriage(dom);
        doctorWorkRequest.setEmergencyContactName(contactname);
        doctorWorkRequest.setEmergencyContactNumber(contactnumber);
        doctorWorkRequest.setCity(city);
        doctorWorkRequest.setBloodPressure(bloodpressure);
        doctorWorkRequest.setHaemoglobin(haemoglobin);
        doctorWorkRequest.setTemperature(temp);
        doctorWorkRequest.setPulse(pulse);
        doctorWorkRequest.setRespiration(resp);
        doctorWorkRequest.setSender((labtestrequest.getReceiver()));
        doctorWorkRequest.setPregnancyPeriod(pregnancyperiod);
        vitalSigns.setPatientName(name);
        vitalSigns.setDateOfBirth(dob);
        vitalSigns.setDateOfMarriage(dom);
        vitalSigns.setEmergencyContactName(contactname);
        vitalSigns.setEmergencyContactNumber(contactnumber);
        vitalSigns.setCity(city);
        vitalSigns.setBloodPressure(bloodpressure);
        vitalSigns.setHaemoglobin(haemoglobin);
        vitalSigns.setTemperature(temp);
        vitalSigns.setPulse(pulse);
        vitalSigns.setRespiration(resp);
        
        
        for (Network network : system.getNetworkList()) {
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        if (enterprise instanceof MCHBEnterprise) {
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                if (organization instanceof DoctorOrganization) {
                                    org = organization;
                                    break;
                                }
                            }
                        }

                    }
                }
                if (org != null) {
                    
                    //System.out.println("userinterface.Farmer.FarmerComplaintRegistrationJPanel.requestTestJButtonActionPerformed()");
                    org.getWorkQueue().getWorkRequestList().add(doctorWorkRequest);
                    userAccount.getWorkQueue().getWorkRequestList().add(doctorWorkRequest);

                    JOptionPane.showMessageDialog(null, "You have successfully added Patient Record !", "Information", JOptionPane.INFORMATION_MESSAGE);

                }
        
       // JOptionPane.showMessageDialog(null, "Patient Report added successfully!");

    }//GEN-LAST:event_addPatientBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bloodPressureTextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField contactNameTextField;
    private javax.swing.JTextField contactnumTextField;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JTextField domTextField;
    private javax.swing.JTextField haemoglobinTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField numMonthsTextField;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JTextField respirationTextField;
    private javax.swing.JTextField tempTextField;
    // End of variables declaration//GEN-END:variables
}
