/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CareTakerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CareTakerOrganization;
import Business.Organization.Organization;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author my pc
 */

public class ManageInformationJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInformationJpanel
     */
    private JPanel userprocessContainer;
    private UserAccount userAccount;
    private CareTakerOrganization careTakerOrganization;
    Organization org;
    private Enterprise enterprise;
    private EcoSystem business;
    private PatientDirectory patientDirectory;
    int count=0;
    int ispregnant=0;
    int refPatient=0;
    public ManageInformationJpanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem business,PatientDirectory patientDirectory) {
        initComponents();
        this.userprocessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.org = organization;
       // this.careTakerOrganization = new CareTakerOrganization();
      this.careTakerOrganization = (CareTakerOrganization) org;
       // System.out.println("caretaker org=" + this.careTakerOrganization);
        this.enterprise = enterprise;
        this.business = business;
     this.patientDirectory=patientDirectory;
     count = calculatePatient();
     countTextField.setText(String.valueOf(count));
     ispregnant =calculateIsPatient();
     isPregTextField.setText(String.valueOf(ispregnant));
     refPatient=calculateRefPatient();
     refCountTextField.setText(String.valueOf(refPatient));
    }
    public int calculatePatient(){
        int count = 0;
        for(WorkRequest request : careTakerOrganization.getWorkQueue().getWorkRequestList()){
            count = count+1;
        }
        return count;
    }
    public int calculateIsPatient(){
        int count = 0;
        for(WorkRequest request : careTakerOrganization.getWorkQueue().getWorkRequestList()){
            if(((LabTestWorkRequest)request).getIsPregnant().equals("Yes")){
                count =count+1;
            }
        }
        return count;
    }
     public int calculateRefPatient(){
        int count = 0;
        for(WorkRequest request : careTakerOrganization.getWorkQueue().getWorkRequestList()){
            if(request.getStatus().equals("Completed"))
            count = count+1;
        }
        return count;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        countTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        isPregTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        refCountTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countTextField.setEnabled(false);
        add(countTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 65, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Total Number of Patients entered by you:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 240, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Patient Count Screen");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 260, -1));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Count of Pregnant Ladies ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        isPregTextField.setEnabled(false);
        add(isPregTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 60, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Count of Patients Referred");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        refCountTextField.setEnabled(false);
        add(refCountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 60, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userprocessContainer.remove(this);
        CardLayout layout = (CardLayout) userprocessContainer.getLayout();
        layout.previous(userprocessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField countTextField;
    private javax.swing.JTextField isPregTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField refCountTextField;
    // End of variables declaration//GEN-END:variables
}
