/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.medicineWorkFlowRequest;
//import Business.WorkQueue.medicineWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vasundhara
 */
public class RequestMedicinesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestMedicinesJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    
    public RequestMedicinesJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        populateMedicineRequestTable();
    }
    
    public void populateMedicineRequestTable(){
        DefaultTableModel dtm = (DefaultTableModel) medicineRequestJTable1.getModel();
        String response = null;
        
        dtm.setRowCount(0);
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request instanceof medicineWorkFlowRequest){
            Object[] row = new Object[5];
            
            medicineWorkFlowRequest mediRequest = (medicineWorkFlowRequest)request;
            row[0] = mediRequest;
            row[1] = mediRequest.getQty();
            row[2] = mediRequest.getStatus();
            row[3] = mediRequest.getReceiver();
            /*if (request instanceof medicineWorkFlowRequest)
                response = ((medicineWorkRequest) request).getMediName();*/
            response = ((medicineWorkFlowRequest) request).getResponse();
            row[4] = response == null ? "Waiting" : response;
            
            dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        medicineJTextField = new javax.swing.JTextField();
        requestMedicineJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        QtyjTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        medicineRequestJTable1 = new javax.swing.JTable();
        RefreshjButton = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 130, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Medicine Name :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, 22));
        add(medicineJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 90, -1));

        requestMedicineJButton.setBackground(new java.awt.Color(0, 0, 0));
        requestMedicineJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        requestMedicineJButton.setForeground(new java.awt.Color(255, 255, 255));
        requestMedicineJButton.setText("Request Medicine");
        requestMedicineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestMedicineJButtonActionPerformed(evt);
            }
        });
        add(requestMedicineJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Quantity :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 108, 100, 22));
        add(QtyjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 90, -1));

        medicineRequestJTable1.setBackground(new java.awt.Color(0, 0, 0));
        medicineRequestJTable1.setForeground(new java.awt.Color(255, 255, 255));
        medicineRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Quantity", "Status", "Receiver", "Response"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(medicineRequestJTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 189, 480, 90));

        RefreshjButton.setBackground(new java.awt.Color(0, 0, 0));
        RefreshjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RefreshjButton.setForeground(new java.awt.Color(255, 255, 255));
        RefreshjButton.setText("Refresh");
        RefreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshjButtonActionPerformed(evt);
            }
        });
        add(RefreshjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 349, 100, -1));

        backjButton1.setBackground(new java.awt.Color(0, 0, 0));
        backjButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backjButton1.setForeground(new java.awt.Color(255, 255, 255));
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Request Medicine Request");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestMedicineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestMedicineJButtonActionPerformed

        if (medicineJTextField.getText().equals("") || QtyjTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter all required details");
            return;
        }
        else{
        String mName = medicineJTextField.getText();
        int qty =0;// = Integer.parseInt(QtyjTextField1.getText());
        
        if (!mName.matches("^[a-zA-Z0-9]*$")) {
                JOptionPane.showMessageDialog(null, "Please enter the Medicine Name using letters and numbers only");
                return;
            }
        
        
        
        try {
                qty = Integer.parseInt(QtyjTextField1.getText());
                //Integer.parseInt(qty);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type in a number for Quantity");
                return;
            }
        
        medicineWorkFlowRequest request = new medicineWorkFlowRequest(mName, qty);

        //medicineWorkFlowRequestRequest request = new medicineWorkFlowRequestRequest();
        //request 
        /*request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");*/
        
        request.setMessage(mName);
        request.setQty(qty);
        //request.setResponse(response);
        request.setSender(userAccount);
        request.setStatus("sent");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PharmacyOrganization){
                org = organization;
                break;
            }
        }
        /*for (Network network : business.getNetworkList()) {
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        if (enterprise instanceof HospitalEnterprise) {
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                                   if (organization instanceof PharmacyOrganization) {
                                    org = organization;
                                    break;
                                }
                                                        
                           }
                        }

                    }
                }*/
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request sent successfully");
        }
        populateMedicineRequestTable();
        
    }

    }//GEN-LAST:event_requestMedicineJButtonActionPerformed

    private void RefreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshjButtonActionPerformed
        // TODO add your handling code here:
        populateMedicineRequestTable();
    }//GEN-LAST:event_RefreshjButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QtyjTextField1;
    private javax.swing.JButton RefreshjButton;
    private javax.swing.JButton backjButton1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField medicineJTextField;
    private javax.swing.JTable medicineRequestJTable1;
    private javax.swing.JButton requestMedicineJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
